### ISSUE TITLE
pop-build is using Py3.7 options, RHEL 7 or 8 ar Py 3.6 hence fails

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/pop-build#5]
pop-build is making use of feature introduced with Py 3.7, namely 'capture_output'.
In order to build on RHEL 7 and REHL 8 which both use Py 3.6, this needs to be changed as follows:

popbuild/popbuild/venv.py
    opts = hub.popbuild.BUILDS[bname]
    ## root = subprocess.run('pyenv root', shell=True, capture_output=True).stdout.strip().decode()
    root = subprocess.run('pyenv root', shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE).stdout.strip().decode()
    avail = set()
    ## for line in subprocess.run('pyenv versions', shell=True, capture_output=True).stdout.strip().decode().split('\n'):
    for line in subprocess.run('pyenv versions', shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE).stdout.strip().decode().split('\n'):
        avail.add(line.strip())

**Comment by thatch45** [comment]
Merged :)
